nodeLinker: node-modules
enableGlobalCache: true
nmMode: hardlinks-local

enableImmutableInstalls: false

packageExtensions:
  gatsby-plugin-typescript@*:
    peerDependencies:
      gatsby: '*'
  gatsby-plugin-image@*:
    peerDependencies:
      '@babel/core': '*'
  gatsby-plugin-feed@*:
    peerDependencies:
      graphql: '*'
