nodeLinker: node-modules
enableGlobalCache: true
nmMode: hardlinks-local

yarnPath: .yarn/releases/yarn-3.6.3.cjs
enableImmutableInstalls: false

packageExtensions:
  gatsby-plugin-typescript@*:
    peerDependencies:
      gatsby: '*'
  gatsby-plugin-image@*:
    peerDependencies:
      '@babel/core': '*'
  gatsby-plugin-feed@*:
    peerDependencies:
      graphql: '*'
